import { Deck, Flashcard } from './types'

export interface CatalogDeckItem extends Deck {
  downloadsCount: number
  ratingScore: number
  authorName: string
  tags: string[]
}

/**
 * 5 Official High-Yield Core Decks pre-loaded for every student
 */
export const OFFICIAL_DECKS: { deck: Deck; cards: Flashcard[] }[] = [
  // Deck 1: Pharmacology Antidotes & Toxins
  {
    deck: {
      id: 'deck-pharma-antidotes',
      title: 'Pharmacology: Essential Antidotes',
      description: 'High-yield specific antidotes, mechanism of reversal, and toxicity presentations for NEET-PG & INI-CET.',
      subject: 'Pharmacology',
      isOfficial: true,
      colorTone: 'brand',
      cardCount: 8,
      createdAt: '2026-08-01T00:00:00Z',
      updatedAt: '2026-08-01T00:00:00Z',
    },
    cards: [
      {
        id: 'card-ph-1',
        deckId: 'deck-pharma-antidotes',
        front: 'What is the specific antidote for Acetaminophen (Paracetamol) toxicity and its mechanism?',
        back: 'N-Acetylcysteine (NAC)',
        explanation: 'Replenishes hepatic glutathione stores and binds directly to the toxic metabolite NAPQI, preventing hepatocyte necrosis.',
        clinicalPearl: 'Most effective within 8 hours of ingestion; guided by the Rumack-Matthew nomogram.',
        mnemonic: 'NAC = Neutralizes Acetaminophen Cytotoxicity',
        subject: 'Pharmacology',
        position: 0,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-ph-2',
        deckId: 'deck-pharma-antidotes',
        front: 'Antidote of choice for Beta-blocker overdose with refractory bradycardia & hypotension?',
        back: 'Glucagon (IV)',
        explanation: 'Glucagon stimulates adenylate cyclase via independent glucagon G-protein receptors, bypassing blocked beta-receptors to increase myocardial cAMP.',
        clinicalPearl: 'Also consider high-dose insulin euglycemia therapy (HIET) and IV lipid emulsion.',
        subject: 'Pharmacology',
        position: 1,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-ph-3',
        deckId: 'deck-pharma-antidotes',
        front: 'Management of acute Organophosphate poisoning (DUMBBELLS toxidrome)?',
        back: 'Atropine (competitive muscarinic antagonist) + Pralidoxime (2-PAM, AChE reactivator)',
        explanation: 'Atropine reverses central and muscarinic signs (bronchorrhea, bradycardia). Pralidoxime reactivates acetylcholinesterase before irreversible "aging" occurs.',
        clinicalPearl: 'Atropinization endpoint is clear chest on auscultation (dry tracheobronchial secretions), NOT pupil dilation.',
        mnemonic: 'Atropine dries secretions; 2-PAM unlocks the enzyme.',
        subject: 'Pharmacology',
        position: 2,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-ph-4',
        deckId: 'deck-pharma-antidotes',
        front: 'Antidote for Methanol and Ethylene Glycol toxicity?',
        back: 'Fomepizole (or IV Ethanol)',
        explanation: 'Fomepizole is a potent competitive inhibitor of alcohol dehydrogenase (ADH), preventing the formation of toxic metabolites (formic acid & oxalic acid).',
        clinicalPearl: 'Methanol causes optic disc hyperemia & snowstorm blindness; Ethylene glycol causes envelope-shaped calcium oxalate crystalluria & acute kidney injury.',
        subject: 'Pharmacology',
        position: 3,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-ph-5',
        deckId: 'deck-pharma-antidotes',
        front: 'Specific reversal agent for Heparin vs Warfarin overdose?',
        back: 'Heparin: Protamine Sulfate | Warfarin: Vitamin K1 + 4-Factor Prothrombin Complex Concentrate (PCC)',
        explanation: 'Protamine sulfate is a strongly basic peptide that chemically neutralizes acidic heparin. 4F-PCC rapidly replenishes factors II, VII, IX, and X.',
        clinicalPearl: 'Protamine dose: 1 mg per 100 units of unfractionated heparin given in the last 2 hours.',
        subject: 'Pharmacology',
        position: 4,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-ph-6',
        deckId: 'deck-pharma-antidotes',
        front: 'Antidote for Benzodiazepine toxicity vs Opioid toxicity?',
        back: 'Benzodiazepines: Flumazenil | Opioids: Naloxone',
        explanation: 'Flumazenil is a competitive GABA-A receptor antagonist. Naloxone is a non-selective pure opioid receptor antagonist with rapid onset.',
        clinicalPearl: 'Caution: Flumazenil can precipitate acute withdrawal seizures in chronic benzodiazepine users or co-ingestion with TCAs.',
        subject: 'Pharmacology',
        position: 5,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-ph-7',
        deckId: 'deck-pharma-antidotes',
        front: 'Specific antidote for Iron toxicity (radiopaque pills on abdominal X-ray)?',
        back: 'Deferoxamine (IV)',
        explanation: 'Chelates free ferric iron (Fe3+) in serum to form ferrioxamine, which is excreted renally giving characteristic "vin rose" (rose wine) colored urine.',
        clinicalPearl: 'Oral chelators include Deferasirox and Deferiprone for chronic iron overload.',
        subject: 'Pharmacology',
        position: 6,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-ph-8',
        deckId: 'deck-pharma-antidotes',
        front: 'Antidote for Cyanide toxicity (bitter almond odor, elevated lactic acidosis)?',
        back: 'Hydroxocobalamin (Vitamin B12a) OR Sodium Nitrite + Sodium Thiosulfate',
        explanation: 'Hydroxocobalamin binds cyanide to form cyanocobalamin (non-toxic B12), excreted in urine.',
        clinicalPearl: 'Hydroxocobalamin turns urine and mucous membranes reddish-brown without causing methemoglobinemia.',
        subject: 'Pharmacology',
        position: 7,
        createdAt: '2026-08-01T00:00:00Z',
      },
    ],
  },

  // Deck 2: Clinical Triads & Pathognomonic Signs
  {
    deck: {
      id: 'deck-clinical-triads',
      title: 'High-Yield Clinical Triads & Signs',
      description: 'Classic diagnostic triads, pentads, and pathognomonic clinical signs frequently tested in exams.',
      subject: 'General Medicine',
      isOfficial: true,
      colorTone: 'gold',
      cardCount: 8,
      createdAt: '2026-08-01T00:00:00Z',
      updatedAt: '2026-08-01T00:00:00Z',
    },
    cards: [
      {
        id: 'card-tr-1',
        deckId: 'deck-clinical-triads',
        front: 'Components of Charcot’s Triad vs Reynolds’ Pentad in Acute Cholangitis?',
        back: 'Charcot Triad: RUQ Pain + Fever with Chills + Jaundice | Reynolds Pentad: Charcot Triad + Hypotension (Shock) + Altered Mental Status',
        explanation: 'Indicates acute obstructive suppurative cholangitis requiring emergent biliary decompression (ERCP).',
        clinicalPearl: 'Do not confuse with Charcot Neurological Triad in Multiple Sclerosis (SIN: Scanning speech, Intention tremor, Nystagmus).',
        subject: 'General Medicine',
        position: 0,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-tr-2',
        deckId: 'deck-clinical-triads',
        front: 'What constitutes Beck’s Triad of Cardiac Tamponade?',
        back: '1. Hypotension\n2. Distended Neck Veins (Elevated JVP)\n3. Muffled / Distant Heart Sounds',
        explanation: 'Occurs due to pericardial fluid accumulation compressing cardiac chambers, preventing diastolic filling.',
        clinicalPearl: 'Key hemodynamic finding: Pulsus Paradoxus (>10 mmHg drop in systolic BP during inspiration) and electrical alternans on ECG.',
        subject: 'Cardiology',
        position: 1,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-tr-3',
        deckId: 'deck-clinical-triads',
        front: 'What is Cushing’s Triad of Raised Intracranial Pressure (ICP)?',
        back: '1. Hypertension (Widened Pulse Pressure)\n2. Bradycardia\n3. Irregular / Depressed Respirations',
        explanation: 'Life-threatening physiological response to brainstem compression and ischemia, indicating imminent brain herniation.',
        clinicalPearl: 'Opposite of shock vital signs (Shock = Hypotension + Tachycardia).',
        subject: 'General Medicine',
        position: 2,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-tr-4',
        deckId: 'deck-clinical-triads',
        front: 'Classic clinical triad of Normal Pressure Hydrocephalus (NPH)?',
        back: '1. Gait Apraxia (Magnetic gait)\n2. Urinary Incontinence\n3. Dementia (Cognitive decline)',
        explanation: 'Enlarged cerebral ventricles with normal opening pressure on lumbar puncture. Lumbar tap test leads to dramatic gait improvement.',
        mnemonic: '"Wet, Wobbly, and Weird" (Incontinence, Ataxia, Dementia).',
        clinicalPearl: 'Gait disturbance is the first and most responsive symptom to CSF shunting (VP Shunt).',
        subject: 'General Medicine',
        position: 3,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-tr-5',
        deckId: 'deck-clinical-triads',
        front: 'Components of Virchow’s Triad for Thrombosis?',
        back: '1. Endothelial Injury\n2. Stasis or Turbulent Blood Flow\n3. Hypercoagulability',
        explanation: 'The three primary pathophysiological determinants of venous and arterial thrombus formation.',
        subject: 'Pathology',
        position: 4,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-tr-6',
        deckId: 'deck-clinical-triads',
        front: 'What is the classic diagnostic triad of Wernicke Encephalopathy?',
        back: '1. Encephalopathy (Acute confusion)\n2. Oculomotor Dysfunction (Nystagmus, Abducens nerve palsy)\n3. Ataxia (Gait unsteadiness)',
        explanation: 'Due to acute Thiamine (Vitamin B1) deficiency, typically in chronic alcohol use disorder or severe malnourishment.',
        clinicalPearl: 'Always administer Thiamine BEFORE IV glucose to prevent precipitating acute Wernicke-Korsakoff syndrome.',
        subject: 'General Medicine',
        position: 5,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-tr-7',
        deckId: 'deck-clinical-triads',
        front: 'What is Whipple’s Triad for Insulinoma / Hypoglycemia?',
        back: '1. Symptoms of hypoglycemia (sweating, palpitations, confusion)\n2. Documented low blood glucose (<55 mg/dL)\n3. Prompt relief of symptoms after glucose administration',
        explanation: 'Confirms true clinical hypoglycemia. Elevated C-peptide and proinsulin with low glucose confirms endogenous insulinoma.',
        subject: 'General Medicine',
        position: 6,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-tr-8',
        deckId: 'deck-clinical-triads',
        front: 'What constitutes Saint’s Triad?',
        back: '1. Gallstones (Cholelithiasis)\n2. Hiatal Hernia\n3. Diverticulosis coli',
        explanation: 'Co-occurrence of these three conditions without a single common etiology, first described by Charles Saint.',
        subject: 'Surgery',
        position: 7,
        createdAt: '2026-08-01T00:00:00Z',
      },
    ],
  },

  // Deck 3: Pathology Hallmark Bodies
  {
    deck: {
      id: 'deck-pathology-bodies',
      title: 'Pathology: Hallmark Inclusion Bodies',
      description: 'Microscopic hallmark inclusion bodies and their definitive disease associations.',
      subject: 'Pathology',
      isOfficial: true,
      colorTone: 'purple',
      cardCount: 6,
      createdAt: '2026-08-01T00:00:00Z',
      updatedAt: '2026-08-01T00:00:00Z',
    },
    cards: [
      {
        id: 'card-pa-1',
        deckId: 'deck-pathology-bodies',
        front: 'Aschoff Bodies and Anitschkow (Caterpillar) cells are pathognomonic for which condition?',
        back: 'Rheumatic Heart Disease (Acute Rheumatic Fever)',
        explanation: 'Aschoff bodies are granulomatous myocardial nodules containing plump reactive histiocytes with wavy chromatin (Anitschkow cells).',
        clinicalPearl: 'Myocarditis is the most common cause of death in acute rheumatic fever.',
        subject: 'Pathology',
        position: 0,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-pa-2',
        deckId: 'deck-pathology-bodies',
        front: 'Negri Bodies on neuronal histopathology are diagnostic of what infection?',
        back: 'Rabies Virus (Lyssavirus)',
        explanation: 'Eosinophilic, sharply demarcated cytoplasmic inclusions found most abundantly in Purkinje cells of the cerebellum and pyramidal cells of the hippocampus.',
        subject: 'Pathology',
        position: 1,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-pa-3',
        deckId: 'deck-pathology-bodies',
        front: 'Auer Rods in blast cytoplasm are diagnostic of which malignancy?',
        back: 'Acute Myeloid Leukemia (AML), especially APML (M3 / PML-RARA t(15;17))',
        explanation: 'Fused lysosomal granules containing peroxidase and acid phosphatase. Presence in Promyelocytic Leukemia carries risk of DIC upon chemotherapy initiation.',
        clinicalPearl: 'APML is treated urgently with All-Trans Retinoic Acid (ATRA) + Arsenic Trioxide.',
        subject: 'Pathology',
        position: 2,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-pa-4',
        deckId: 'deck-pathology-bodies',
        front: 'Psammoma Bodies (laminated, concentric calcifications) are classic in which malignancies?',
        back: 'PSaMMoma: Papillary Thyroid Carcinoma, Serous Ovarian Cystadenocarcinoma, Meningioma, Mesothelioma',
        explanation: 'Arise from concentric calcification of necrotic papillae tips.',
        mnemonic: 'PSaMMoma: Papillary thyroid, Serous ovary, Meningioma, Mesothelioma.',
        subject: 'Pathology',
        position: 3,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-pa-5',
        deckId: 'deck-pathology-bodies',
        front: 'Lewy Bodies composed of alpha-synuclein are seen in which disorders?',
        back: 'Parkinson’s Disease & Dementia with Lewy Bodies (DLB)',
        explanation: 'Intracellular eosinophilic inclusions composed of aggregated misfolded alpha-synuclein in substantia nigra dopaminergic neurons and cerebral cortex.',
        clinicalPearl: 'DLB presents with early visual hallucinations, REM sleep behavior disorder, and fluctuations in cognition BEFORE motor parkinsonism.',
        subject: 'Pathology',
        position: 4,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-pa-6',
        deckId: 'deck-pathology-bodies',
        front: 'Councilman Bodies on liver biopsy represent what cellular process?',
        back: 'Apoptosis of hepatocytes (Acidophilic bodies)',
        explanation: 'Deeply eosinophilic, rounded apoptotic hepatocyte fragments seen in Yellow Fever, Acute Viral Hepatitis, and Toxic liver injury.',
        subject: 'Pathology',
        position: 5,
        createdAt: '2026-08-01T00:00:00Z',
      },
    ],
  },

  // Deck 4: Microbiology Drugs of Choice
  {
    deck: {
      id: 'deck-microbiology-doc',
      title: 'Microbiology: First-Line Drugs of Choice',
      description: 'Definitive first-line antimicrobials for high-yield bacterial, fungal, and parasitic pathogens.',
      subject: 'Microbiology',
      isOfficial: true,
      colorTone: 'info',
      cardCount: 6,
      createdAt: '2026-08-01T00:00:00Z',
      updatedAt: '2026-08-01T00:00:00Z',
    },
    cards: [
      {
        id: 'card-mi-1',
        deckId: 'deck-microbiology-doc',
        front: 'First-line antimicrobial for Clostridioides difficile colitis?',
        back: 'Oral Fidaxomicin (200 mg BID x 10d) OR Oral Vancomycin (125 mg QID x 10d)',
        explanation: 'Fidaxomicin has lower recurrence rates due to minimal disruption of normal colonic flora. Oral Vancomycin is an equally effective first-line option.',
        clinicalPearl: 'IV Vancomycin is ineffective because it does not achieve therapeutic lumen concentrations in the colon.',
        subject: 'Microbiology',
        position: 0,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-mi-2',
        deckId: 'deck-microbiology-doc',
        front: 'Drug of choice for Treponema pallidum (Syphilis) across all stages?',
        back: 'Benzathine Penicillin G (IM)',
        explanation: 'Primary/Secondary/Early latent: Single dose 2.4 million units IM. Late latent / Tertiary: 2.4 million units IM weekly for 3 weeks.',
        clinicalPearl: 'Neurosyphilis requires IV Aqueous Crystalline Penicillin G for 10-14 days. Penicillin-allergic pregnant patients MUST undergo desensitization.',
        subject: 'Microbiology',
        position: 1,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-mi-3',
        deckId: 'deck-microbiology-doc',
        front: 'Induction therapy of choice for Cryptococcal Meningitis in HIV/AIDS?',
        back: 'Liposomal Amphotericin B + Flucytosine for 2 weeks, followed by Fluconazole consolidation',
        explanation: 'Amphotericin B binds ergosterol, while Flucytosine inhibits fungal DNA synthesis. Combination demonstrates rapid CSF sterilization.',
        clinicalPearl: 'Cryptococcus neoformans is encapsulated, narrow-based budding yeast visualized with India Ink and mucicarmine.',
        subject: 'Microbiology',
        position: 2,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-mi-4',
        deckId: 'deck-microbiology-doc',
        front: 'Drug of choice for Pneumocystis jirovecii pneumonia (PCP) in immunocompromised patients?',
        back: 'Trimethoprim-Sulfamethoxazole (TMP-SMX) High Dose',
        explanation: 'Inhibits sequential steps in folate synthesis. Add systemic corticosteroids if PaO2 < 70 mmHg or A-a gradient ≥ 35 mmHg.',
        subject: 'Microbiology',
        position: 3,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-mi-5',
        deckId: 'deck-microbiology-doc',
        front: 'First-line therapy for visceral Leishmaniasis (Kala-azar) in India?',
        back: 'Single-dose Liposomal Amphotericin B (10 mg/kg)',
        explanation: 'Highly effective cure (>95%) with minimal nephrotoxicity compared to conventional deoxycholate amphotericin B or antimonials.',
        clinicalPearl: 'Vector is the female Phlebotomus argentipes sandfly; amastigote LD bodies in splenic/bone marrow aspirates.',
        subject: 'Microbiology',
        position: 4,
        createdAt: '2026-08-01T00:00:00Z',
      },
      {
        id: 'card-mi-6',
        deckId: 'deck-microbiology-doc',
        front: 'Drug of choice for Pseudomonas aeruginosa bacteremia / sepsis?',
        back: 'Piperacillin-Tazobactam OR Cefepime OR Meropenem / Imipenem',
        explanation: 'Antipseudomonal beta-lactams with high bactericidal activity against Gram-negative rod Pseudomonas.',
        subject: 'Microbiology',
        position: 5,
        createdAt: '2026-08-01T00:00:00Z',
      },
    ],
  },
]

/**
 * Extended Catalog Decks for 1-click download from the Deck Store / Catalog
 */
export const CATALOG_DECKS: CatalogDeckItem[] = [
  {
    id: 'catalog-cardio-ecg',
    title: 'Cardiology: Murmurs & 12-Lead ECG Localization',
    description: 'Aortic vs Mitral valvular lesions, dynamic auscultation maneuvers, and coronary artery MI territories.',
    subject: 'Cardiology',
    downloadsCount: 1420,
    ratingScore: 4.9,
    authorName: 'Mantis High-Yield Medical Team',
    colorTone: 'brand',
    tags: ['ECG', 'Murmurs', 'Cardio', 'Rapid Recall'],
    cardCount: 12,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'catalog-neuro-tracts',
    title: 'Neurology: Brainstem Syndromes & Spinal Tracts',
    description: 'Wallenberg, Weber, Millard-Gubler, and Brown-Séquard syndrome lesion localizations.',
    subject: 'Neurology',
    downloadsCount: 980,
    ratingScore: 4.8,
    authorName: 'Dr. Kabir Mehta, JIPMER',
    colorTone: 'purple',
    tags: ['Neuroanatomy', 'Strokes', 'Localisation'],
    cardCount: 10,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'catalog-obgyn-milestones',
    title: 'OB-GYN: High-Yield Obstetrics & Bishop Score',
    description: 'CTG decelerations, postpartum hemorrhage management protocols, and gestational trophoblastic disease.',
    subject: 'Obstetrics & Gynaecology',
    downloadsCount: 1150,
    ratingScore: 4.9,
    authorName: 'Dr. Priya Nair, AIIMS New Delhi',
    colorTone: 'rose',
    tags: ['OBGYN', 'CTG', 'Labor', 'Bishop Score'],
    cardCount: 14,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'catalog-peds-milestones',
    title: 'Pediatrics: Developmental Milestones & Vaccines',
    description: 'Gross motor, fine motor, language, and social developmental checkpoints from 2 months to 5 years + NIS Schedule.',
    subject: 'Pediatrics',
    downloadsCount: 890,
    ratingScore: 4.7,
    authorName: 'Mantis Pediatrics Faculty',
    colorTone: 'gold',
    tags: ['Development', 'Vaccines', 'Pediatrics'],
    cardCount: 12,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
]
